### ISSUE TITLE
Highlighting Options in LibComp

### ISSUE THREAD

**Issue by relhajj** [ualberta-smr/LibCompPlugin#10]
Need to decide whether we will keep highlighting a line w/ a package or not. 

User should be able to control this. Give them the option to click on "No longer highlight alternatives for X domain" in the interface. 

Also, what if they click do not show X domain and then later change their mind, what then? Therefore, should be somewhere to re-set.

**Comment by snadi** [comment]
Confirmed that this is solved in PR #38:

![image](https://user-images.githubusercontent.com/2363957/94824721-a258ac80-0405-11eb-9e71-90defd57a3b3.png)

![image](https://user-images.githubusercontent.com/2363957/94824813-b1d7f580-0405-11eb-8d92-ca66c947a2ca.png)
