### ISSUE TITLE
REST api response formatting

### ISSUE THREAD

**Issue by relhajj** [ualberta-smr/LibCompPlugin#20]
Right now, the json responses are actually not recognized as json format b/c there are no surrounding curly brackets at the beginning and end. 

Format should be like this:

Libraries { 
ALL OF THE JSON, EXACTLY AS IT IS NOW
}

As a workaround, I just added the "Libraries {"  and "}" at the beginning and end then the json library im using could recognize it and everything worked out fine. 

If we change the API response, it will just remove that one extra step I have in my code.

**Comment by snadi** [comment]
Can you check if this changes if you retrieve a *json* response from the http request

**Comment by relhajj** [comment]
closing issue because the functionality is fine without changing the {} curly brackets. For future reference if this issue is reopened, the problem was that the json library was not recognizing the GET response as a json file until I manually added curly brackets to the response.

**Comment by snadi** [comment]
Can you point to where in the code is this handling done, in case we want to change it in the future?
