### ISSUE TITLE
Intsallable plugin should work on older versions 

### ISSUE THREAD

**Issue by relhajj** [ualberta-smr/LibCompPlugin#22]
Plugin is packaged a an intelliJ 2020 version plugin, so it seems to be incompatible with 2019 (or previous) versions. 

Look into a solution so that the plugin works for multiple version of intelliJ

**Comment by relhajj** [comment]
Refer to https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000620084-how-to-build-a-plugin-that-is-compatible-to-multiple-versions-of-IntelliJ-

**Comment by Hk-tang** [comment]
I encountered an issue when installing the plugin from scratch. 
```
Plugin 'LibraryComparison' is incompatible with this installation: until build 201.SNAPSHOT < IU-202.6948.69
```
I fixed it by setting `updateSinceUntilBuild` to false in the build.gradle. However, I am not sure this is the best solution for it.
```
intellij {
    version '2020.1.1'
    plugins 'java'
    updateSinceUntilBuild false
}
```

**Comment by snadi** [comment]
@Hk-tang which intelliJ version were you using?

From my side, I can confirm that it works with 2020.1.1, but I'm not sure if it can work with older versions (e.g., 2019) or newer versions (e.g., Issue #40)
