### ISSUE TITLE
Colors don't appear well in dark mode & buttons disappear

### ISSUE THREAD

**Issue by snadi** [ualberta-smr/LibCompPlugin#43]
We still have the problem of colors not showing well in dark mode, but worse the buttons disappear once I start interacting with the dialog (e.g., clicking on the sort up/down buttons):

![image](https://user-images.githubusercontent.com/2363957/94898520-ff01a900-0491-11eb-8ea5-88bb6f11b7d3.png)

The color choice is something we can fix later, but @relhajj, do you do anything on sorting that could cause the buttons to disappear?

**Comment by snadi** [comment]
Actually same thing happens in light mode:

![image](https://user-images.githubusercontent.com/2363957/95082229-07b8e000-071b-11eb-93e6-7e5855543ec9.png)

**Comment by XiaoleZ** [comment]
The button will disappear when
1. click Library Comparison and the window pop-up
2. click other window or app (or just the desktop) other than the pop-up window
3. click the white space at the bottom of Library Comparison Window
4. The button will disappear

The button will show up when I click any data in the table.
