### ISSUE TITLE
Data collection optimization

### ISSUE THREAD

**Issue by relhajj** [ualberta-smr/LibCompPlugin#9]
Look into optimizing the way we collect data for the library comparison website (esp. popularity) 

First do popularity, but if time permits, look into other metric data collection that could use some optimization. 

PROBLEM:
- Also, apparently there is an  issue in that when the popularity script is run, it will collect up to ~720 repo's and then stop. Look into this problem and see whether optimization will fix it. 
- Could it be that github is limiting the amount of data we are allowed to query in a set time period?

**Comment by snadi** [comment]
Related to scripts, issue opened and address there. Closing here
